# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153jc46qT2e9mh6JqKXzKPgBANYAu_set
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the shopping_trends dataset
file_path = 'shopping_trends.csv'
shopping_trends = pd.read_csv('/content/sample_data/shopping_trends.csv')

print("First few rows of the shopping_trends dataset:")
print(shopping_trends.head())

# Check for missing values
print("\nMissing values in the shopping_trends dataset:")
print(shopping_trends.isnull().sum())

# Summary statistics for Item Purchased
print("\nSummary statistics for Item Purchased:")
print(shopping_trends['Item Purchased'].describe())

# Ratings distribution
plt.figure(figsize=(10, 6))
sns.histplot(movies_df['Item Purchased'], bins=10, kde=False, color='skyblue', edgecolor='black')
plt.xlabel('Item Purchased')
plt.ylabel('Frequency')
plt.title('Distribution of Item Purchased')

# Highly Purchased Amount rate
plt.figure(figsize=(12, 8))
sns.countplot(y='Purchase Amount (USD)', data=movies_df, order=movies_df['Purchase Amount (USD)'].value_counts().index, palette='viridis')
plt.xlabel('Count')
plt.ylabel('Purchase Amount (USD)')
plt.title('Highly Purchased Amount rate ')

# Top-rated items
top_rated_movies = movies_df.sort_values(by='Review Rating', ascending=False).head(10)
plt.figure(figsize=(12, 8))
sns.barplot(x='Review Rating', y='Item Purchased', data=top_rated_movies, palette='plasma')
plt.xlabel('Review Rating')
plt.ylabel('Item Purchased')
plt.title('Top 10 Highest Item Purchased ')
# Show the plots
plt.show()